version: '3.8'

services:
  app:
    container_name: backend
    build: .
    command: pnpm start
    ports:
      - "3000:3000"
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
    depends_on:
      - postgres_production
      - postgres_development
  postgres_production:
    container_name: postgres-production
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/app/postgres-production:/var/lib/postgres/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=estadao
  postgres_development:
    container_name: postgres-development
    image: postgres:16-alpine
    ports:
      - 5433:5432
    volumes:
      - ~/app/postgres-development:/var/lib/postgres/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=estadao_dev
